# Generated by Django 2.0.9 on 2019-12-10 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20191210_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='user_project', through='project_app.UserProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
