# Generated by Django 2.0.9 on 2019-12-23 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0004_auto_20191210_0835'),
        ('issue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_issues', to='project_app.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='creator_issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='target_issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
