# Generated by Django 2.0.9 on 2019-12-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_app', '0002_auto_20191223_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='target_issue',
            new_name='target_user',
        ),
    ]
