# Generated by Django 2.0.9 on 2019-12-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_app', '0003_auto_20191223_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='application',
            new_name='project',
        ),
    ]
